### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [mbieniek/FacebookImagePicker#1]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by mbieniek** [comment]
Hi @mansya, sure I'd be happy to accept a PR for a new logo/icon!

**Comment by mansya** [comment]
I have design a logo for this project. what do you think ? do you like it ?
![facebookimagepicker](https://user-images.githubusercontent.com/33461607/42723761-9d5d16b2-878e-11e8-82b1-3a16375aec7c.png)

**Comment by mbieniek** [comment]
Looks great!

**Comment by mansya** [comment]
I have upload all files to this link
https://drive.google.com/open?id=1WxIEhTYgJlFDIW5XqqkgvgfEViszPX80

And I have sent you pull requests. please check it.

**Comment by mbieniek** [comment]
@mansya Thank you for the contribution!
